rule "child1"
extends "parent"
when
then
    System.out.println("Output Child1.1");
    System.out.println("Output Change Child1.1");
end

rule "child2"
extends "parent"
when
then
    System.out.println("Output Child2");
    System.out.println("Output Change Child2");
end


rule "child3"
extends "child1"
when
then
    System.out.println("Output Child3.1");
    System.out.println("Output Change Child3.1");
end

rule "child4"
extends "parent"
when
then
    System.out.println("Output Child4");
    System.out.println("Output Change Child4");
end

